# Generated by Django 5.2.6 on 2025-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('app', 'Application'), ('website', 'Website')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BlockedApp',
        ),
    ]
